export { default as Hero, type Props as IHero } from './Hero.astro'
export { default as About, type Props as IAbout } from './About.astro'
export { default as Customers, type Props as ICustomers } from './Customers.astro'
export { default as Services, type Props as IServices } from './Services.astro'
export { default as Stats, type Props as IStats } from './Stats.astro'